run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/navikt/copilot

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
