// Code generated by scripts/sync-copilot-models.mjs; DO NOT EDIT.
// Regenerate with: mise run models:sync  (source: models.dev github-copilot provider)

package domain

// KnownCopilotModels is the curated Copilot model list, generated from the
// models.dev github-copilot catalog plus a short pinned set (see the generator's
// PINNED list: the "auto" pseudo-model and delisted-but-working models kept on
// purpose).
//
// It lives in domain rather than internal/provider because two packages need
// the same pairing and cannot import each other: provider builds the launch
// flags and the pickers from it, and internal/artifacts resolves an agent's
// frontmatter model label against it while materializing opencode agents.
// provider imports artifacts, so domain, which both import, is the only home
// that keeps one table instead of two.
var KnownCopilotModels = []ModelChoice{
	{ID: "auto", Label: "Auto (let Copilot pick)"},
	{ID: "claude-fable-5", Label: "Claude Fable 5"},
	{ID: "claude-fable-5.1", Label: "Claude Fable 5.1"},
	{ID: "claude-haiku-4.5", Label: "Claude Haiku 4.5 (latest)"},
	{ID: "claude-opus-4.6", Label: "Claude Opus 4.6"},
	{ID: "claude-opus-4.7", Label: "Claude Opus 4.7"},
	{ID: "claude-opus-4.8", Label: "Claude Opus 4.8"},
	{ID: "claude-opus-5", Label: "Claude Opus 5"},
	{ID: "claude-sonnet-4.6", Label: "Claude Sonnet 4.6"},
	{ID: "claude-sonnet-5", Label: "Claude Sonnet 5"},
	{ID: "gemini-3.5-flash", Label: "Gemini 3.5 Flash"},
	{ID: "gemini-3.6-flash", Label: "Gemini 3.6 Flash"},
	{ID: "gemini-3.7-flash", Label: "Gemini 3.7 Flash"},
	{ID: "gemini-3.8-flash", Label: "Gemini 3.8 Flash"},
	{ID: "gpt-5-mini", Label: "GPT-5 Mini"},
	{ID: "gpt-5.3-codex", Label: "GPT-5.3 Codex"},
	{ID: "gpt-5.4", Label: "GPT-5.4"},
	{ID: "gpt-5.4-mini", Label: "GPT-5.4 mini"},
	{ID: "gpt-5.4-nano", Label: "GPT-5.4 nano"},
	{ID: "gpt-5.5", Label: "GPT-5.5"},
	{ID: "gpt-5.6-luna", Label: "GPT-5.6 Luna"},
	{ID: "gpt-5.6-sol", Label: "GPT-5.6 Sol"},
	{ID: "gpt-5.6-terra", Label: "GPT-5.6 Terra"},
	{ID: "gpt-6-astra", Label: "GPT-6 Astra"},
	{ID: "grok-4.5", Label: "Grok 4.5"},
	{ID: "grok-4.6", Label: "Grok 4.6"},
	{ID: "kimi-k2.7-code", Label: "Kimi K2.7 Code"},
	{ID: "kimi-k3", Label: "Kimi K3"},
	{ID: "mai-code-1-flash-picker", Label: "MAI-Code-1-Flash"},
	{ID: "mai-code-1.1-flash", Label: "MAI-Code-1.1-Flash"},
}
