package cli

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/charmbracelet/huh"

	providerpkg "github.com/navikt/copilot/cli/nav-pilot/internal/provider"
)

// setupAnswers holds the answers collected by the first-run config wizard.
// Model and ReasoningEffort are empty string when the user chose to leave them unset.
type setupAnswers struct {
	Client          string
	Model           string // empty = don't write the key
	Mode            string
	ReasoningEffort string // empty = don't write the key
	AutoUpdate      string // "true" or "false"
}

// writeSetupConfig writes a new config file from wizard answers.
// It uses the existing formatTOMLValue helpers so the output is consistent
// with what 'config set' would produce.
// The config is validated before writing; an error is returned if it is invalid.
func writeSetupConfig(answers setupAnswers) error {
	if answers.Client == "" {
		answers.Client = "copilot"
	}
	if answers.Mode == "" {
		answers.Mode = "default"
	}

	var lines []string
	lines = append(lines,
		"# nav-pilot configuration",
		"# Generated by: nav-pilot config setup",
		"# Edit directly or run 'nav-pilot config set <key> <value>' to change.",
		"",
		"# Configuration schema version. Must be 1.",
		"version = 1",
		"",
	)

	// Preserve a persisted agentpakke source: the wizard does not ask about it,
	// and rewriting the file must not silently drop the user's selection (B2).
	if existing, err := readConfig(); err == nil && existing != nil && existing.Source != nil {
		if persisted := strings.TrimSpace(*existing.Source); persisted != "" {
			sourceVal, _ := formatTOMLValue(findKeyDef("source"), persisted)
			lines = append(lines, "source = "+sourceVal)
		}
	}

	// The client is always written: a later change of the built-in default
	// must not move a user who answered this (#1029). For the rest only what
	// differs from the default is written, so a later default reaches them.
	clientVal, _ := formatTOMLValue(findKeyDef("client"), answers.Client)
	lines = append(lines, "client = "+clientVal)
	if answers.Mode != findKeyDef("mode").defaultVal {
		modeVal, _ := formatTOMLValue(findKeyDef("mode"), answers.Mode)
		lines = append(lines, "mode = "+modeVal)
	}

	if answers.Model != "" {
		modelVal, _ := formatTOMLValue(findKeyDef("model"), answers.Model)
		lines = append(lines, "model = "+modelVal)
	}
	if answers.ReasoningEffort != "" {
		effortVal, _ := formatTOMLValue(findKeyDef("reasoning_effort"), answers.ReasoningEffort)
		lines = append(lines, "reasoning_effort = "+effortVal)
	}

	if answers.AutoUpdate != "" && answers.AutoUpdate != findKeyDef("auto_update").defaultVal {
		lines = append(lines, "auto_update = "+answers.AutoUpdate)
	}

	content := strings.Join(lines, "\n") + "\n"

	// Validate before writing.
	var cfg Config
	if _, err := toml.Decode(content, &cfg); err != nil {
		return fmt.Errorf("internal error building config TOML: %w", err)
	}
	if err := validateConfig(&cfg); err != nil {
		return fmt.Errorf("internal error: generated config is invalid: %w", err)
	}

	return writeConfigFile(configPath(), []byte(content), nil)
}

// runConfigSetupFn is overridable in tests, the way cmdSyncFn is: the wizard
// itself needs a terminal, so the only way to assert what reaches it is to
// stand in for it.
var runConfigSetupFn = runConfigSetup

// runConfigSetup runs the interactive first-run wizard.
// Returns nil on user cancel (so callers never block).
// Each huh prompt: on cancel/error, print a soft notice and return nil.
//
// flagSource is the --source the command line carried, or "" when it carried
// none. It is the flag half of the source precedence, and the wizard needs it
// because first-run setup happens before the config file exists: a first run
// with a custom source has nowhere else to learn it from (#813).
func runConfigSetup(flagSource string) error {
	fmt.Println()
	fmt.Printf("%s  First-run setup\n", bold("🧭 nav-pilot"))
	fmt.Println(dim("  Set your preferences — change anytime with 'nav-pilot config set'."))
	fmt.Println()

	// Preselected answers are the built-in defaults, except the client of
	// a config this run replaces (config setup --force): an existing user
	// keeps theirs unless they pick another (#1022).
	answers := setupAnswers{
		Client:     findKeyDef("client").defaultVal,
		Mode:       findKeyDef("mode").defaultVal,
		AutoUpdate: findKeyDef("auto_update").defaultVal,
	}
	opencodeLabel := clientLabel["opencode"] + " (default)"
	if existing, err := readConfig(); err == nil && existing != nil {
		answers.Client = cfgClient(existing)
		opencodeLabel = clientLabel["opencode"]
	}

	err := huh.NewSelect[string]().
		Title("Which coding agent?").
		Options(
			huh.NewOption(opencodeLabel, "opencode"),
			huh.NewOption(clientLabel["copilot"], "copilot"),
			huh.NewOption(clientLabel["pi"], "pi"),
		).
		Value(&answers.Client).
		WithTheme(navTheme()).
		Run()
	if err != nil {
		return setupSkipped(err)
	}
	if answers.Client == "opencode" {
		if answers.Client, err = opencodeForSetup(); err != nil {
			return setupSkipped(err)
		}
	}

	err = huh.NewSelect[string]().
		Title("Conversation mode").
		Options(
			huh.NewOption("default", "default"),
			huh.NewOption("plan — think before acting", "plan"),
			huh.NewOption("autopilot — no confirmations", "autopilot"),
		).
		Value(&answers.Mode).
		WithTheme(navTheme()).
		Run()
	if err != nil {
		return setupSkipped(err)
	}

	// Model picker: providers with a curated model list get a select widget;
	// others (pi, unknown future providers) get a free-text input.
	p, _ := providerFor(answers.Client)
	modelDesc := "Pick a model, or leave it unset for the agentpakke's default (the agent's own if it names none)."
	if p != nil && p.DefaultModel() != "" {
		modelDesc = "Pick a model (provider/model format), or leave unset to use the Nav default."
	}
	model, err := promptModel(p, "Model", modelDesc, "")
	if err != nil {
		return setupSkipped(err)
	}
	answers.Model = model

	err = huh.NewSelect[string]().
		Title("Reasoning effort").
		Description("Controls how hard the model thinks. Leave unset to use the agent default.").
		Options(
			huh.NewOption("Unset (the agent's own default)", ""),
			huh.NewOption("none", "none"),
			huh.NewOption("low", "low"),
			huh.NewOption("medium", "medium"),
			huh.NewOption("high", "high"),
			huh.NewOption("xhigh", "xhigh"),
			huh.NewOption("max", "max"),
		).
		Value(&answers.ReasoningEffort).
		WithTheme(navTheme()).
		Run()
	if err != nil {
		return setupSkipped(err)
	}

	err = huh.NewSelect[string]().
		Title("Auto-update nav-pilot").
		Description("Automatically install new CLI versions in the background.").
		Options(
			huh.NewOption("Yes", "true"),
			huh.NewOption("No: say when a new version is out, and ask to upgrade once 7 days behind", "false"),
		).
		Value(&answers.AutoUpdate).
		WithTheme(navTheme()).
		Run()
	if err != nil {
		return setupSkipped(err)
	}

	if err := writeSetupConfig(answers); err != nil {
		return fmt.Errorf("saving config: %w", err)
	}

	// Bootstrap the selected provider on first run (e.g. opencode: write OTel config
	// and seed Nav context so the user is immediately ready without a separate step).
	//
	// The --source this run carried, else the file the wizard just wrote
	// (writeSetupConfig preserves a persisted source), so a user with their own
	// pakke gets that pakke seeded rather than the built-in default (#813) —
	// the same precedence every other source lookup uses. A bad value is not
	// worth aborting setup over: the seeding is the optional part.
	if p != nil {
		seedSource, srcErr := sourceRepoFor(flagSource)
		if srcErr != nil {
			fmt.Fprintf(os.Stderr, "%s Could not read the configured source: %v\n", yellow("⚠"), srcErr)
		}
		if summary, ctxErr := p.Bootstrap(ResolvedConfig{Client: answers.Client, Source: seedSource}); ctxErr != nil {
			fmt.Fprintf(os.Stderr, "%s Could not seed Nav context for %s: %v\n", yellow("⚠"), p.DisplayName(), ctxErr)
		} else if summary != "" {
			fmt.Printf("  %s Nav context seeded: %s\n", green("✓"), summary)
		}
	}

	path := configPath()
	fmt.Printf("\n%s Saved %s\n", green("✓"), path)
	fmt.Println()
	fmt.Println("  Change settings anytime:")
	fmt.Printf("    %s\n", dim("nav-pilot config set <key> <value>"))
	fmt.Printf("    %s\n", dim("edit "+path+" directly"))
	fmt.Printf("    %s\n", dim("pass CLI flags per run (e.g. --client opencode)"))
	fmt.Println()

	return nil
}

// opencodeForSetup settles a wizard answer of opencode on a machine without
// it: when the user says yes, Homebrew installs it, or without Homebrew
// opencode's own install script does. Otherwise the wizard saves copilot and
// says how to switch later, naming both clients when neither is installed. It
// never saves a client that cannot start. Nothing is run without the yes.
func opencodeForSetup() (string, error) {
	if opencodeInstalled() {
		return "opencode", nil
	}
	_, brewErr := exec.LookPath("brew")
	withBrew := brewErr == nil
	desc := "Runs " + opencodeBrewInstall + "."
	if !withBrew {
		desc = "Runs " + opencodeScriptInstall + ", opencode's own installer. It puts opencode in ~/.opencode/bin and adds that to PATH in your shell's config."
	}
	install := true
	if err := huh.NewConfirm().
		Title("opencode is not installed. Install it now?").
		Description(desc).
		Affirmative("Install").
		Negative("Use GitHub Copilot instead").
		Value(&install).
		WithTheme(navTheme()).
		Run(); errors.Is(err, huh.ErrUserAborted) {
		return "", err
	} else if err != nil {
		install = false // a prompt that could not run is no answer
	}
	if install {
		used, cmd := opencodeBrewInstall, exec.Command("brew", "install", "anomalyco/tap/opencode")
		if !withBrew {
			used, cmd = opencodeScriptInstall, exec.Command(bashPath(), "-c", opencodeScriptInstall)
		}
		cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
		err := cmd.Run()
		if err == nil && !withBrew {
			// The script adds its directory to PATH in the shell's config,
			// which this process never reads.
			if home, herr := os.UserHomeDir(); herr == nil {
				os.Setenv("PATH", filepath.Join(home, ".opencode", "bin")+string(os.PathListSeparator)+os.Getenv("PATH"))
			}
		}
		if err == nil && opencodeInstalled() {
			fmt.Printf("  %s opencode installed\n", green("✓"))
			return "opencode", nil
		}
		if err == nil {
			err = errors.New("opencode is still not on PATH")
		}
		fmt.Fprintf(os.Stderr, "%s %s: %v\n", yellow("⚠"), used, err)
	}
	if p, err := providerFor("copilot"); err == nil && !p.Available() {
		fmt.Printf("  Neither opencode nor GitHub Copilot is installed. nav-pilot saves GitHub Copilot for now. Install one of them:\n    opencode: %s, then %s\n    GitHub Copilot CLI: %s\n",
			opencodeInstallCommand(), bold("nav-pilot config set client opencode"), providerpkg.CopilotInstallCommand)
		return "copilot", nil
	}
	fmt.Printf("  opencode is not installed, so nav-pilot will use GitHub Copilot. To switch later, install opencode (%s), then run %s\n",
		opencodeInstallCommand(), bold("nav-pilot config set client opencode"))
	return "copilot", nil
}

// opencodeScriptInstall is opencode's own installer, for a machine without
// Homebrew.
const opencodeScriptInstall = "curl -fsSL https://opencode.ai/install | bash"

// bashPath is bash from PATH, else /bin/bash: the opencode installer needs
// bash, not sh.
func bashPath() string {
	if p, err := exec.LookPath("bash"); err == nil {
		return p
	}
	return "/bin/bash"
}

// opencodeBrewInstall is opencode's recommended Homebrew install.
const opencodeBrewInstall = "brew install anomalyco/tap/opencode"

// opencodeInstallCommand is how to install opencode on this machine:
// Homebrew when it is there, otherwise opencode's install script.
func opencodeInstallCommand() string {
	if _, err := exec.LookPath("brew"); err == nil {
		return opencodeBrewInstall
	}
	return opencodeScriptInstall
}

// setupSkipped is how the wizard ends when a prompt returns err. Ctrl-C ends
// the whole run, and the wizard has written nothing yet. Any other error is a
// prompt that could not run: the wizard steps aside with one line and the run
// goes on without a config.
func setupSkipped(err error) error {
	if errors.Is(err, huh.ErrUserAborted) {
		return cancelledError{nothingWritten: true}
	}
	fmt.Println(dim("  Setup skipped — run 'nav-pilot config setup' anytime."))
	return nil
}

// maybeRunFirstRunSetup runs the config wizard on the first interactive run.
// It is a no-op when any of the following are true:
//   - the terminal is not interactive (isInteractive() == false)
//   - the config file already exists
func maybeRunFirstRunSetup(flagSource string) error {
	if !isInteractive() {
		return nil
	}
	if _, err := os.Stat(configPath()); !errors.Is(err, os.ErrNotExist) {
		// File exists (err == nil) or some other stat error — skip setup.
		return nil
	}
	return runConfigSetupFn(flagSource)
}

// cmdConfigSetup implements the 'nav-pilot config setup' subcommand.
// It touches nothing until the wizard has every answer: the existing file is
// replaced, with a backup, only by the wizard's final atomic write.
func cmdConfigSetup(force bool) error {
	_, statErr := os.Stat(configPath())
	exists := statErr == nil
	if !isInteractive() {
		left := ""
		if exists {
			left = "; your config was left as it is"
		}
		return fmt.Errorf("config setup needs a terminal%s. To script it, use nav-pilot config set <key> <value>", left)
	}
	if exists && !force {
		// Ask instead of refusing: the launch error that sent the user here
		// says to start over, and a refusal would send them round again.
		if err := huh.NewConfirm().
			Title(fmt.Sprintf("%s already exists. Replace it?", configPath())).
			Affirmative("Replace").
			Negative("Keep it").
			Value(&force).
			WithTheme(navTheme()).
			Run(); errors.Is(err, huh.ErrUserAborted) {
			return cancelledError{nothingWritten: true}
		} else if err != nil {
			force = false // a prompt that could not run is no answer: keep the file
		}
		if !force {
			fmt.Printf("Kept %s.\n", configPath())
			return nil
		}
	}
	// No flag source: `config setup` does not persist one, so seeding from a
	// --source would materialize a pakke the config it just wrote never names.
	return runConfigSetupFn("")
}
