/**
 * GitHub Copilot model pricing data.
 * Source: https://docs.github.com/en/copilot/reference/copilot-billing/models-and-pricing
 * Last updated: 2026-06-29
 *
 * All prices are per 1 million tokens in USD.
 * 1 AI credit = $0.01 USD.
 *
 * AUTO-GENERATED by scripts/sync-model-pricing.mjs — do not edit manually.
 */

export interface ModelPrice {
  model: string;
  provider: "OpenAI" | "Anthropic" | "Google" | "GitHub";
  category: "Lightweight" | "Versatile" | "Powerful";
  status: "GA" | "Public preview";
  input: number;
  cachedInput: number;
  cacheWrite?: number;
  output: number;
  note?: string;
}

export const MODEL_PRICING: ModelPrice[] = [
  // OpenAI
  {
    model: "GPT-5 mini (Default)",
    provider: "OpenAI",
    category: "Lightweight",
    status: "GA",
    input: 0.25,
    cachedInput: 0.025,
    output: 2,
  },
  {
    model: "GPT-5.3-Codex (Default)",
    provider: "OpenAI",
    category: "Powerful",
    status: "GA",
    input: 1.75,
    cachedInput: 0.175,
    output: 14,
  },
  {
    model: "GPT-5.4 (Default, ≤ 272K)",
    provider: "OpenAI",
    category: "Versatile",
    status: "GA",
    input: 2.5,
    cachedInput: 0.25,
    output: 15,
  },
  {
    model: "GPT-5.4 (Long context, > 272K)",
    provider: "OpenAI",
    category: "Versatile",
    status: "GA",
    input: 5,
    cachedInput: 0.5,
    output: 22.5,
  },
  {
    model: "GPT-5.4 mini (Default)",
    provider: "OpenAI",
    category: "Lightweight",
    status: "GA",
    input: 0.75,
    cachedInput: 0.075,
    output: 4.5,
  },
  {
    model: "GPT-5.4 nano (Default)",
    provider: "OpenAI",
    category: "Lightweight",
    status: "GA",
    input: 0.2,
    cachedInput: 0.02,
    output: 1.25,
  },
  {
    model: "GPT-5.5 (Default, ≤ 272K)",
    provider: "OpenAI",
    category: "Powerful",
    status: "GA",
    input: 5,
    cachedInput: 0.5,
    output: 30,
  },
  {
    model: "GPT-5.5 (Long context, > 272K)",
    provider: "OpenAI",
    category: "Powerful",
    status: "GA",
    input: 10,
    cachedInput: 1,
    output: 45,
  },
  // Anthropic
  {
    model: "Claude Haiku 4.5",
    provider: "Anthropic",
    category: "Versatile",
    status: "GA",
    input: 1,
    cachedInput: 0.1,
    cacheWrite: 1.25,
    output: 5,
  },
  {
    model: "Claude Sonnet 4",
    provider: "Anthropic",
    category: "Versatile",
    status: "GA",
    input: 3,
    cachedInput: 0.3,
    cacheWrite: 3.75,
    output: 15,
  },
  {
    model: "Claude Sonnet 4.5",
    provider: "Anthropic",
    category: "Versatile",
    status: "GA",
    input: 3,
    cachedInput: 0.3,
    cacheWrite: 3.75,
    output: 15,
  },
  {
    model: "Claude Sonnet 4.6",
    provider: "Anthropic",
    category: "Versatile",
    status: "GA",
    input: 3,
    cachedInput: 0.3,
    cacheWrite: 3.75,
    output: 15,
  },
  {
    model: "Claude Opus 4.5",
    provider: "Anthropic",
    category: "Powerful",
    status: "GA",
    input: 5,
    cachedInput: 0.5,
    cacheWrite: 6.25,
    output: 25,
  },
  {
    model: "Claude Opus 4.6",
    provider: "Anthropic",
    category: "Powerful",
    status: "GA",
    input: 5,
    cachedInput: 0.5,
    cacheWrite: 6.25,
    output: 25,
  },
  {
    model: "Claude Opus 4.7",
    provider: "Anthropic",
    category: "Powerful",
    status: "GA",
    input: 5,
    cachedInput: 0.5,
    cacheWrite: 6.25,
    output: 25,
  },
  {
    model: "Claude Opus 4.8",
    provider: "Anthropic",
    category: "Powerful",
    status: "GA",
    input: 5,
    cachedInput: 0.5,
    cacheWrite: 6.25,
    output: 25,
  },
  {
    model: "Claude Opus 4.8 (fast mode) (preview)",
    provider: "Anthropic",
    category: "Powerful",
    status: "GA",
    input: 10,
    cachedInput: 1,
    cacheWrite: 12.5,
    output: 50,
  },
  {
    model: "Claude Fable 5",
    provider: "Anthropic",
    category: "Powerful",
    status: "GA",
    input: 10,
    cachedInput: 1,
    cacheWrite: 12.5,
    output: 50,
  },
  // Google
  {
    model: "Gemini 2.5 Pro (Default)",
    provider: "Google",
    category: "Powerful",
    status: "GA",
    input: 1.25,
    cachedInput: 0.125,
    output: 10,
  },
  {
    model: "Gemini 3 Flash (Default)",
    provider: "Google",
    category: "Lightweight",
    status: "Public preview",
    input: 0.5,
    cachedInput: 0.05,
    output: 3,
  },
  {
    model: "Gemini 3.1 Pro (Default, ≤ 200K)",
    provider: "Google",
    category: "Powerful",
    status: "Public preview",
    input: 2,
    cachedInput: 0.2,
    output: 12,
  },
  {
    model: "Gemini 3.1 Pro (Long context, > 200K)",
    provider: "Google",
    category: "Powerful",
    status: "Public preview",
    input: 4,
    cachedInput: 0.4,
    output: 18,
  },
  {
    model: "Gemini 3.5 Flash (Default)",
    provider: "Google",
    category: "Lightweight",
    status: "GA",
    input: 1.5,
    cachedInput: 0.15,
    output: 9,
  },
  // GitHub
  {
    model: "Raptor mini",
    provider: "GitHub",
    category: "Versatile",
    status: "GA",
    input: 0.25,
    cachedInput: 0.025,
    output: 2,
  },
];

export const PRICING_SOURCE_URL = "https://docs.github.com/en/copilot/reference/copilot-billing/models-and-pricing";
export const PRICING_LAST_UPDATED = "2026-06-29";
