use std::fmt::Write;
use std::path::{Path, PathBuf};

/// Sensitive directories under $HOME that are always denied.
const DENIED_DOTFILES: &[&str] = &[
    ".ssh",
    ".gnupg",
    ".aws",
    ".azure",
    ".kube",
    ".docker",
    ".nais",
    ".password-store",
];

/// Sensitive files under $HOME that are always denied.
const DENIED_FILES: &[&str] = &[".netrc", ".npmrc", ".pypirc", ".gem/credentials"];

/// System files that tools commonly need (SSL certs, resolv.conf, etc.)
const SYSTEM_READ_FILES: &[&str] = &[
    "/private/etc/ssl",
    "/private/etc/resolv.conf",
    "/private/etc/hosts",
    "/private/etc/shells",
    "/private/etc/passwd",
    "/private/etc/localtime",
    "/private/etc/zshrc",
    "/private/etc/bashrc",
    "/private/etc/profile",
];

/// Tool directories commonly needed by developers.
const TOOL_READ_DIRS: &[&str] = &["/usr/local", "/opt/homebrew"];

/// Tool directories under $HOME that get read access.
const HOME_TOOL_DIRS: &[&str] = &[
    ".local",
    ".mise",
    ".nvm",
    ".cargo",
    ".rustup",
    "go",
    "Library/Caches",
];

/// Generate a complete SBPL sandbox profile.
pub fn generate_profile(
    project_dir: &Path,
    home_dir: &Path,
    extra_read: &[PathBuf],
    extra_write: &[PathBuf],
    extra_deny: &[PathBuf],
    proxy_port: Option<u16>,
) -> String {
    let mut sb = String::with_capacity(4096);
    let home = home_dir.to_string_lossy();
    let project = project_dir.to_string_lossy();

    // Header
    writeln!(sb, ";; Auto-generated by copilot-sandbox").unwrap();
    writeln!(sb, ";; Project: {project}").unwrap();
    writeln!(sb, "(version 1)").unwrap();
    writeln!(sb, "(deny default)").unwrap();
    writeln!(sb).unwrap();

    // Base system profile
    writeln!(sb, "(import \"/System/Library/Sandbox/Profiles/bsd.sb\")").unwrap();
    writeln!(sb).unwrap();

    // Process execution
    writeln!(sb, ";; Process execution").unwrap();
    writeln!(sb, "(allow process-exec)").unwrap();
    writeln!(sb, "(allow process-fork)").unwrap();
    writeln!(sb).unwrap();

    // Project directory — full access
    writeln!(sb, ";; Project directory — full read/write").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"{project}\"))").unwrap();
    writeln!(sb, "(allow file-write* (subpath \"{project}\"))").unwrap();
    writeln!(sb).unwrap();

    // Copilot config — the CLI needs its auth tokens and settings
    writeln!(sb, ";; Copilot config").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"{home}/.copilot\"))").unwrap();
    writeln!(sb, "(allow file-write* (subpath \"{home}/.copilot\"))").unwrap();
    writeln!(sb).unwrap();

    // macOS Keychain access — Copilot stores auth tokens here
    writeln!(sb, ";; macOS Keychain (Copilot auth tokens)").unwrap();
    writeln!(
        sb,
        "(allow file-read* (subpath \"{home}/Library/Keychains\"))"
    )
    .unwrap();
    writeln!(
        sb,
        "(allow mach-lookup (global-name \"com.apple.securityd\"))"
    )
    .unwrap();
    writeln!(
        sb,
        "(allow mach-lookup (global-name \"com.apple.SecurityServer\"))"
    )
    .unwrap();
    writeln!(sb).unwrap();

    // Git config (read-only)
    writeln!(sb, ";; Git config (read-only)").unwrap();
    writeln!(sb, "(allow file-read* (literal \"{home}/.gitconfig\"))").unwrap();
    writeln!(
        sb,
        "(allow file-read* (literal \"{home}/.config/git/config\"))"
    )
    .unwrap();
    writeln!(sb).unwrap();

    // Developer tool directories
    writeln!(sb, ";; Developer tools").unwrap();
    for dir in TOOL_READ_DIRS {
        writeln!(sb, "(allow file-read* (subpath \"{dir}\"))").unwrap();
        writeln!(sb, "(allow file-map-executable (subpath \"{dir}\"))").unwrap();
    }
    for dir in HOME_TOOL_DIRS {
        writeln!(sb, "(allow file-read* (subpath \"{home}/{dir}\"))").unwrap();
    }
    writeln!(sb).unwrap();

    // System config files (specific, not broad)
    writeln!(sb, ";; System config (specific files)").unwrap();
    for path in SYSTEM_READ_FILES {
        if path.contains('/') && !path.ends_with('/') {
            // Could be a file or directory — use subpath for dirs like /private/etc/ssl
            if path.ends_with("ssl") {
                writeln!(sb, "(allow file-read* (subpath \"{path}\"))").unwrap();
            } else {
                writeln!(sb, "(allow file-read* (literal \"{path}\"))").unwrap();
            }
        } else {
            writeln!(sb, "(allow file-read* (literal \"{path}\"))").unwrap();
        }
    }
    writeln!(sb).unwrap();

    // Temp directories
    writeln!(sb, ";; Temp directories").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"/private/tmp\"))").unwrap();
    writeln!(sb, "(allow file-write* (subpath \"/private/tmp\"))").unwrap();
    writeln!(sb, "(allow file-read* (subpath \"/private/var/folders\"))").unwrap();
    writeln!(sb, "(allow file-write* (subpath \"/private/var/folders\"))").unwrap();
    writeln!(sb).unwrap();

    // Extra user-specified allows
    if !extra_read.is_empty() || !extra_write.is_empty() {
        writeln!(sb, ";; User-specified allows").unwrap();
        for path in extra_read {
            let p = path.to_string_lossy();
            writeln!(sb, "(allow file-read* (subpath \"{p}\"))").unwrap();
        }
        for path in extra_write {
            let p = path.to_string_lossy();
            writeln!(sb, "(allow file-read* (subpath \"{p}\"))").unwrap();
            writeln!(sb, "(allow file-write* (subpath \"{p}\"))").unwrap();
        }
        writeln!(sb).unwrap();
    }

    // Sensitive directories — DENY (after allows, so these override)
    writeln!(sb, ";; Sensitive directories — DENIED").unwrap();
    for dotfile in DENIED_DOTFILES {
        writeln!(sb, "(deny file-read* (subpath \"{home}/{dotfile}\"))").unwrap();
        writeln!(sb, "(deny file-write* (subpath \"{home}/{dotfile}\"))").unwrap();
    }
    for file in DENIED_FILES {
        writeln!(sb, "(deny file-read* (literal \"{home}/{file}\"))").unwrap();
        writeln!(sb, "(deny file-write* (literal \"{home}/{file}\"))").unwrap();
    }
    for path in extra_deny {
        let p = path.to_string_lossy();
        writeln!(sb, "(deny file-read* (subpath \"{p}\"))").unwrap();
        writeln!(sb, "(deny file-write* (subpath \"{p}\"))").unwrap();
    }
    writeln!(sb).unwrap();

    // Network — deny all, allow only the proxy port (or nothing)
    writeln!(sb, ";; Network — deny all outbound except proxy").unwrap();
    writeln!(sb, "(deny network*)").unwrap();
    writeln!(
        sb,
        "(allow network-outbound (literal \"/private/var/run/mDNSResponder\"))"
    )
    .unwrap();
    writeln!(sb, "(allow network-outbound (remote unix-socket))").unwrap();

    if let Some(port) = proxy_port {
        writeln!(
            sb,
            "(allow network-outbound (remote ip \"localhost:{port}\"))"
        )
        .unwrap();
        writeln!(
            sb,
            "(allow network-inbound (local ip \"localhost:{port}\"))"
        )
        .unwrap();
    }
    // No else — without proxy, ALL outbound is blocked

    sb
}

/// Validate the profile by running a simple command inside the sandbox.
pub fn validate(profile_path: &Path, _project_dir: &Path, _home_dir: &Path) -> Result<(), String> {
    let output = std::process::Command::new("sandbox-exec")
        .arg("-f")
        .arg(profile_path)
        .arg("/usr/bin/true")
        .output()
        .map_err(|e| format!("Failed to run sandbox-exec: {e}"))?;

    if output.status.success() {
        Ok(())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        Err(format!(
            "sandbox-exec exited with {}: {stderr}",
            output.status
        ))
    }
}

/// Execute copilot inside the sandbox, forwarding signals to the child process group.
pub fn exec(
    profile_path: &Path,
    project_dir: &Path,
    _home_dir: &Path,
    copilot_args: &[String],
    proxy_env: &[(String, String)],
) -> u8 {
    use std::os::unix::process::CommandExt;

    let mut cmd = std::process::Command::new("sandbox-exec");
    cmd.arg("-f").arg(profile_path).arg("copilot");

    for arg in copilot_args {
        cmd.arg(arg);
    }

    // Set proxy env vars
    for (key, val) in proxy_env {
        cmd.env(key, val);
    }

    // Set working directory to project
    cmd.current_dir(project_dir);

    // Start child in its own process group for clean signal forwarding
    unsafe {
        cmd.pre_exec(|| {
            libc::setpgid(0, 0);
            Ok(())
        });
    }

    let mut child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("\x1b[0;31m[sandbox]\x1b[0m Failed to start sandbox-exec: {e}");
            return 1;
        }
    };

    let child_pid = child.id() as i32;

    // Install signal handlers that forward to child process group
    install_signal_forwarding(child_pid);

    match child.wait() {
        Ok(status) => status.code().unwrap_or(1) as u8,
        Err(e) => {
            eprintln!("\x1b[0;31m[sandbox]\x1b[0m Error waiting for child: {e}");
            // Kill the process group on error
            unsafe {
                libc::killpg(child_pid, libc::SIGTERM);
            }
            1
        }
    }
}

fn install_signal_forwarding(child_pgid: i32) {
    use std::sync::atomic::{AtomicI32, Ordering};

    static CHILD_PGID: AtomicI32 = AtomicI32::new(0);
    CHILD_PGID.store(child_pgid, Ordering::SeqCst);

    extern "C" fn forward_signal(sig: i32) {
        use std::sync::atomic::Ordering;
        let pgid = CHILD_PGID.load(Ordering::SeqCst);
        if pgid > 0 {
            unsafe {
                libc::killpg(pgid, sig);
            }
        }
    }

    unsafe {
        libc::signal(
            libc::SIGINT,
            forward_signal as *const () as libc::sighandler_t,
        );
        libc::signal(
            libc::SIGTERM,
            forward_signal as *const () as libc::sighandler_t,
        );
        libc::signal(
            libc::SIGHUP,
            forward_signal as *const () as libc::sighandler_t,
        );
    }
}
