package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/charmbracelet/huh"
)

// setupAnswers holds the answers collected by the first-run config wizard.
// Model and ReasoningEffort are empty string when the user chose to leave them unset.
type setupAnswers struct {
	Agent           string
	Model           string // empty = don't write the key
	Mode            string
	ReasoningEffort string // empty = don't write the key
}

// writeSetupConfig writes a new config file from wizard answers.
// It uses the existing formatTOMLValue helpers so the output is consistent
// with what 'config set' would produce.
// The config is validated before writing; an error is returned if it is invalid.
func writeSetupConfig(answers setupAnswers) error {
	if answers.Agent == "" {
		answers.Agent = "copilot"
	}
	if answers.Mode == "" {
		answers.Mode = "default"
	}

	var lines []string
	lines = append(lines,
		"# nav-pilot configuration",
		"# Generated by: nav-pilot config setup",
		"# Edit directly or run 'nav-pilot config set <key> <value>' to change.",
		"",
		"# Configuration schema version. Must be 1.",
		"version = 1",
		"",
	)

	agentVal, _ := formatTOMLValue(findKeyDef("agent"), answers.Agent)
	lines = append(lines, "agent = "+agentVal)

	modeVal, _ := formatTOMLValue(findKeyDef("mode"), answers.Mode)
	lines = append(lines, "mode = "+modeVal)

	if answers.Model != "" {
		modelVal, _ := formatTOMLValue(findKeyDef("model"), answers.Model)
		lines = append(lines, "model = "+modelVal)
	}
	if answers.ReasoningEffort != "" {
		effortVal, _ := formatTOMLValue(findKeyDef("reasoning_effort"), answers.ReasoningEffort)
		lines = append(lines, "reasoning_effort = "+effortVal)
	}

	content := strings.Join(lines, "\n") + "\n"

	// Validate before writing.
	var cfg Config
	if _, err := toml.Decode(content, &cfg); err != nil {
		return fmt.Errorf("internal error building config TOML: %w", err)
	}
	if err := validateConfig(&cfg); err != nil {
		return fmt.Errorf("internal error: generated config is invalid: %w", err)
	}

	path := configPath()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("creating config directory: %w", err)
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// runConfigSetup runs the interactive first-run wizard.
// Returns nil on user cancel (so callers never block).
// Each huh prompt: on cancel/error, print a soft notice and return nil.
func runConfigSetup() error {
	fmt.Println()
	fmt.Printf("%s  First-run setup\n", bold("🧭 nav-pilot"))
	fmt.Println(dim("  Set your preferences — change anytime with 'nav-pilot config set'."))
	fmt.Println()

	answers := setupAnswers{
		Agent: "copilot",
		Mode:  "default",
	}

	err := huh.NewSelect[string]().
		Title("Which coding agent?").
		Options(
			huh.NewOption("GitHub Copilot (default)", "copilot"),
			huh.NewOption("OpenCode", "opencode"),
			huh.NewOption("π (pi)", "pi"),
		).
		Value(&answers.Agent).
		WithTheme(navTheme()).
		Run()
	if err != nil {
		fmt.Println(dim("  Setup skipped — run 'nav-pilot config setup' anytime."))
		return nil
	}

	err = huh.NewSelect[string]().
		Title("Conversation mode").
		Options(
			huh.NewOption("default", "default"),
			huh.NewOption("plan — think before acting", "plan"),
			huh.NewOption("autopilot — no confirmations", "autopilot"),
		).
		Value(&answers.Mode).
		WithTheme(navTheme()).
		Run()
	if err != nil {
		fmt.Println(dim("  Setup skipped — run 'nav-pilot config setup' anytime."))
		return nil
	}

	err = huh.NewInput().
		Title("Model (leave blank for agent default)").
		Description("Any model name accepted — validated by the downstream CLI.").
		Placeholder("e.g. gpt-4o, auto").
		Value(&answers.Model).
		WithTheme(navTheme()).
		Run()
	if err != nil {
		fmt.Println(dim("  Setup skipped — run 'nav-pilot config setup' anytime."))
		return nil
	}

	err = huh.NewSelect[string]().
		Title("Reasoning effort").
		Description("Controls how hard the model thinks. Leave unset to use the agent default.").
		Options(
			huh.NewOption("Unset (agent default)", ""),
			huh.NewOption("none", "none"),
			huh.NewOption("low", "low"),
			huh.NewOption("medium", "medium"),
			huh.NewOption("high", "high"),
			huh.NewOption("xhigh", "xhigh"),
			huh.NewOption("max", "max"),
		).
		Value(&answers.ReasoningEffort).
		WithTheme(navTheme()).
		Run()
	if err != nil {
		fmt.Println(dim("  Setup skipped — run 'nav-pilot config setup' anytime."))
		return nil
	}

	if err := writeSetupConfig(answers); err != nil {
		return fmt.Errorf("saving config: %w", err)
	}

	path := configPath()
	fmt.Printf("\n%s Saved %s\n", green("✓"), path)
	fmt.Println()
	fmt.Println("  Change settings anytime:")
	fmt.Printf("    %s\n", dim("nav-pilot config set <key> <value>"))
	fmt.Printf("    %s\n", dim("edit "+path+" directly"))
	fmt.Printf("    %s\n", dim("pass CLI flags per run (e.g. --agent opencode)"))
	fmt.Println()

	return nil
}

// maybeRunFirstRunSetup runs the config wizard on the first interactive run.
// It is a no-op when any of the following are true:
//   - the terminal is not interactive (isInteractive() == false)
//   - the config file already exists
func maybeRunFirstRunSetup() error {
	if !isInteractive() {
		return nil
	}
	if _, err := os.Stat(configPath()); !errors.Is(err, os.ErrNotExist) {
		// File exists (err == nil) or some other stat error — skip setup.
		return nil
	}
	return runConfigSetup()
}

// cmdConfigSetup implements the 'nav-pilot config setup' subcommand.
// Refuses to clobber an existing config and directs the user to 'config set'.
func cmdConfigSetup() error {
	if _, err := os.Stat(configPath()); err == nil {
		return fmt.Errorf("config file already exists: %s\n\nTo update individual settings:  %s\nTo see current settings:        %s\nTo replace entirely: delete the file and re-run 'nav-pilot config setup'.",
			configPath(),
			bold("nav-pilot config set <key> <value>"),
			bold("nav-pilot config show"))
	}
	if !isInteractive() {
		return fmt.Errorf("config setup requires an interactive terminal.\n\nUse 'nav-pilot config init' to create a template, then edit it directly.")
	}
	return runConfigSetup()
}
