package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
)

// ─── Key definitions ─────────────────────────────────────────────────────────

type keyKind int

const (
	keyKindString keyKind = iota
	keyKindInt
	keyKindBool
)

type configKeyDef struct {
	name        string
	kind        keyKind
	description string
	allowed     []string // nil = any non-empty string
	defaultVal  string   // empty = no default / unset
	flag        string   // corresponding Copilot CLI flag
}

var configKeyDefs = []configKeyDef{
	{
		name:        "version",
		kind:        keyKindInt,
		description: "Configuration schema version. Must be 1.",
		allowed:     []string{"1"},
		defaultVal:  "",
		flag:        "",
	},
	{
		name:        "client",
		kind:        keyKindString,
		description: "Coding-agent CLI to launch (copilot, opencode, pi).",
		allowed:     validProviderIDs,
		defaultVal:  "copilot",
		flag:        "--client",
	},
	{
		name:        "model",
		kind:        keyKindString,
		description: "Model id (e.g. auto, claude-opus-4.8, gpt-5.5). Format-validated; the catalog is checked downstream.",
		allowed:     nil,
		defaultVal:  "",
		flag:        "--model",
	},
	{
		name:        "mode",
		kind:        keyKindString,
		description: "Copilot conversation mode.",
		allowed:     validModes,
		defaultVal:  "default",
		flag:        "--mode",
	},
	{
		name:        "reasoning_effort",
		kind:        keyKindString,
		description: "Reasoning effort level.",
		allowed:     validReasoningEffort,
		defaultVal:  "",
		flag:        "--effort",
	},
	{
		name:        "context_tier",
		kind:        keyKindString,
		description: "Context window tier.",
		allowed:     validContextTiers,
		defaultVal:  "",
		flag:        "--context",
	},
	{
		name:        "allow_all_tools",
		kind:        keyKindBool,
		description: "Allow all tools without per-tool confirmation.",
		allowed:     nil,
		defaultVal:  "false",
		flag:        "--allow-all-tools",
	},
	{
		name:        "ask_user",
		kind:        keyKindBool,
		description: "Ask the user before taking actions. Set to false to disable.",
		allowed:     nil,
		defaultVal:  "true",
		flag:        "--no-ask-user (when false)",
	},
	{
		name:        "log_level",
		kind:        keyKindString,
		description: "Log level for Copilot CLI output.",
		allowed:     validLogLevels,
		defaultVal:  "",
		flag:        "--log-level",
	},
	{
		name:        "otel_log_level",
		kind:        keyKindString,
		description: "OpenTelemetry diagnostic log level for the Copilot CLI (OTEL_LOG_LEVEL). Defaults to none to suppress telemetry connection-error spam.",
		allowed:     validOtelLogLevels,
		defaultVal:  "none",
		flag:        "--otel-log-level",
	},
}

func findKeyDef(name string) *configKeyDef {
	for i := range configKeyDefs {
		if configKeyDefs[i].name == name {
			return &configKeyDefs[i]
		}
	}
	return nil
}

func knownKeyNames() string {
	names := make([]string, len(configKeyDefs))
	for i, kd := range configKeyDefs {
		names[i] = kd.name
	}
	return strings.Join(names, ", ")
}

// ─── Init template ────────────────────────────────────────────────────────────

const configInitTemplate = `# nav-pilot configuration
# Generated by: nav-pilot config init
# Override path: NAV_PILOT_CONFIG=/path/to/config.toml
# Uncomment and edit the options you want to customize.

# Configuration schema version. Must be 1.
version = 1

# Coding-agent CLI nav-pilot launches.
# Allowed: copilot, opencode, pi — Default: copilot
# client = "copilot"

# Model id. Common Copilot models: auto, claude-sonnet-4.6, claude-haiku-4.5,
# claude-opus-4.8, claude-opus-4.6, gpt-5.5, gpt-5.4, gpt-5.3-codex,
# gpt-5.4-mini, gpt-5-mini, gemini-3.1-pro-preview, gemini-3.5-flash.
# For opencode use provider/model (e.g. anthropic/claude-3-5-sonnet).
# Format-validated locally; the model catalog is checked by the downstream CLI.
# Default: agent-specific default
# Corresponds to Copilot CLI flag: --model
# model = "auto"

# Copilot conversation mode.
# Allowed: default, plan, autopilot — Default: default
# Corresponds to Copilot CLI flag: --mode
# mode = "default"

# Reasoning effort level.
# Allowed: none, low, medium, high, xhigh, max — Default: unset (agent default)
# Corresponds to Copilot CLI flag: --effort
# reasoning_effort = "medium"

# Context window tier.
# Allowed: default, long_context — Default: unset (agent default)
# Corresponds to Copilot CLI flag: --context
# context_tier = "default"

# Allow all tools without per-tool confirmation.
# Default: false
# Corresponds to Copilot CLI flag: --allow-all-tools
# allow_all_tools = false

# Ask the user before taking actions. Set to false to disable.
# Default: true
# Corresponds to Copilot CLI flag: --no-ask-user (when false)
# ask_user = true

# Log level for Copilot CLI output.
# Allowed: none, error, warning, info, debug, all, default — Default: unset
# Corresponds to Copilot CLI flag: --log-level
# log_level = "info"

# OpenTelemetry diagnostic log level for the Copilot CLI (sets OTEL_LOG_LEVEL).
# Allowed: none, error, warning, warn, info, debug, verbose, all — Default: none
# Keep this at "none" to suppress Copilot telemetry connection-error spam when
# the OTLP endpoint is unreachable. A pre-existing OTEL_LOG_LEVEL in your shell
# environment takes precedence.
# otel_log_level = "none"
`

// ─── Subcommand dispatch ──────────────────────────────────────────────────────

func cmdConfig(args []string, jsonOutput bool) error {
	if len(args) == 0 {
		return fmt.Errorf("config requires a subcommand.\n\nUsage: nav-pilot config <subcommand> [options]\n\nSubcommands:\n  init      Create ~/.nav-pilot/config.toml with all options commented out\n  setup     Run the interactive first-run setup wizard\n  show      Print effective configuration (file values merged with defaults)\n  path      Print the config file path\n  get       Print one key value\n  set       Set a key value (creates file if missing)\n  validate  Validate config syntax, unknown keys, and values\n  explain   Describe configuration keys")
	}

	sub := args[0]
	rest := args[1:]

	switch sub {
	case "init":
		return cmdConfigInit()
	case "setup":
		return cmdConfigSetup()
	case "show":
		return cmdConfigShow(jsonOutput)
	case "path":
		return cmdConfigPath()
	case "get":
		if len(rest) == 0 {
			return fmt.Errorf("config get requires a key.\n\nUsage: nav-pilot config get <key>\n\nKnown keys: %s", knownKeyNames())
		}
		return cmdConfigGet(rest[0])
	case "set":
		if len(rest) < 2 {
			return fmt.Errorf("config set requires a key and value.\n\nUsage: nav-pilot config set <key> <value>")
		}
		return cmdConfigSet(rest[0], rest[1])
	case "validate":
		return cmdConfigValidate()
	case "explain":
		key := ""
		if len(rest) > 0 {
			key = rest[0]
		}
		return cmdConfigExplain(key)
	default:
		return fmt.Errorf("unknown config subcommand: %q\n\nSubcommands: init, setup, show, path, get, set, validate, explain", sub)
	}
}

// ─── config init ─────────────────────────────────────────────────────────────

func cmdConfigInit() error {
	path := configPath()

	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("config file already exists: %s\n\nUse %s to see current values, or edit the file directly",
			path, bold("nav-pilot config show"))
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("checking config path: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("creating config directory: %w", err)
	}
	if err := os.WriteFile(path, []byte(configInitTemplate), 0o600); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	fmt.Printf("%s Created %s\n", green("✓"), path)
	fmt.Printf("  Edit the file or use %s to set individual options.\n", bold("nav-pilot config set"))
	return nil
}

// ─── config show ─────────────────────────────────────────────────────────────

func cmdConfigShow(jsonOutput bool) error {
	cfg, err := readConfig()
	if err != nil {
		return err
	}
	resolved := resolve(cfg, CLIOverrides{})

	if jsonOutput {
		return outputJSON(map[string]interface{}{
			"client":           resolved.Client,
			"model":            resolved.Model,
			"mode":             resolved.Mode,
			"reasoning_effort": resolved.ReasoningEffort,
			"context_tier":     resolved.ContextTier,
			"allow_all_tools":  resolved.AllowAllTools,
			"ask_user":         resolved.AskUser,
			"log_level":        resolved.LogLevel,
			"otel_log_level":   resolved.OtelLogLevel,
		})
	}

	path := configPath()
	if cfg == nil {
		fmt.Printf("# Config file: %s %s\n\n", path, dim("(not found, using defaults)"))
	} else {
		fmt.Printf("# Config file: %s\n\n", path)
	}

	printField := func(key, val, src string) {
		if val == "" {
			fmt.Printf("  %-20s = %-20s (%s)\n", key, "(unset)", src)
		} else {
			fmt.Printf("  %-20s = %-20s (%s)\n", key, val, src)
		}
	}
	printBoolField := func(key string, val bool, src string) {
		fmt.Printf("  %-20s = %-20s (%s)\n", key, strconv.FormatBool(val), src)
	}

	clientSrc := "default"
	if cfg != nil && cfg.Client != nil {
		clientSrc = "file"
	}
	printField("client", resolved.Client, clientSrc)

	modelSrc := "unset"
	if cfg != nil && cfg.Model != nil {
		modelSrc = "file"
	}
	printField("model", resolved.Model, modelSrc)

	modeSrc := "default"
	if cfg != nil && cfg.Mode != nil {
		modeSrc = "file"
	}
	printField("mode", resolved.Mode, modeSrc)

	effortSrc := "unset"
	if cfg != nil && cfg.ReasoningEffort != nil {
		effortSrc = "file"
	}
	printField("reasoning_effort", resolved.ReasoningEffort, effortSrc)

	tierSrc := "unset"
	if cfg != nil && cfg.ContextTier != nil {
		tierSrc = "file"
	}
	printField("context_tier", resolved.ContextTier, tierSrc)

	toolsSrc := "default"
	if cfg != nil && cfg.AllowAllTools != nil {
		toolsSrc = "file"
	}
	printBoolField("allow_all_tools", resolved.AllowAllTools, toolsSrc)

	askSrc := "default"
	if cfg != nil && cfg.AskUser != nil {
		askSrc = "file"
	}
	printBoolField("ask_user", resolved.AskUser, askSrc)

	logSrc := "unset"
	if cfg != nil && cfg.LogLevel != nil {
		logSrc = "file"
	}
	printField("log_level", resolved.LogLevel, logSrc)

	otelSrc := "default"
	if cfg != nil && cfg.OtelLogLevel != nil {
		otelSrc = "file"
	}
	printField("otel_log_level", resolved.OtelLogLevel, otelSrc)

	return nil
}

// ─── config path ─────────────────────────────────────────────────────────────

func cmdConfigPath() error {
	fmt.Println(configPath())
	return nil
}

// ─── config get ──────────────────────────────────────────────────────────────

func cmdConfigGet(key string) error {
	kd := findKeyDef(key)
	if kd == nil {
		return fmt.Errorf("unknown key: %q\n\nKnown keys: %s", key, knownKeyNames())
	}

	cfg, err := readConfig()
	if err != nil {
		return err
	}
	resolved := resolve(cfg, CLIOverrides{})

	val := resolvedFieldStr(resolved, key)
	fmt.Println(val)
	return nil
}

// resolvedFieldStr returns the string representation of a resolved field.
func resolvedFieldStr(r ResolvedConfig, key string) string {
	switch key {
	case "version":
		return "1" // version is always 1 when valid
	case "client":
		return r.Client
	case "model":
		return r.Model
	case "mode":
		return r.Mode
	case "reasoning_effort":
		return r.ReasoningEffort
	case "context_tier":
		return r.ContextTier
	case "allow_all_tools":
		return strconv.FormatBool(r.AllowAllTools)
	case "ask_user":
		return strconv.FormatBool(r.AskUser)
	case "log_level":
		return r.LogLevel
	case "otel_log_level":
		return r.OtelLogLevel
	}
	return ""
}

// ─── config set ──────────────────────────────────────────────────────────────

func cmdConfigSet(key, value string) error {
	kd := findKeyDef(key)
	if kd == nil {
		return fmt.Errorf("unknown key: %q\n\nKnown keys: %s", key, knownKeyNames())
	}
	if err := validateKeyValue(kd, value); err != nil {
		return err
	}

	tomlVal, err := formatTOMLValue(kd, value)
	if err != nil {
		return err
	}
	newLine := key + " = " + tomlVal

	path := configPath()

	// Read existing content (if any).
	var lines []string
	data, err := os.ReadFile(path)
	if err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("reading config: %w", err)
		}
		// New file: seed the required schema version so the resulting config
		// passes on-launch validation (validateConfig requires version = 1).
		lines = []string{"version = 1"}
	} else {
		lines = strings.Split(string(data), "\n")
		// Remove trailing empty element from trailing newline.
		if len(lines) > 0 && lines[len(lines)-1] == "" {
			lines = lines[:len(lines)-1]
		}
	}

	// Find and replace the first matching line (active or commented-out).
	found := false
	for i, line := range lines {
		if isConfigKeyLine(line, key) {
			lines[i] = newLine
			found = true
			break
		}
	}
	if !found {
		lines = append(lines, newLine)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("creating config directory: %w", err)
	}
	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}
	if err := os.Chmod(path, 0o600); err != nil {
		return fmt.Errorf("setting config permissions: %w", err)
	}

	fmt.Printf("%s %s = %s\n", green("✓"), key, tomlVal)
	return nil
}

// isConfigKeyLine returns true if line (active or commented-out) represents the given key.
func isConfigKeyLine(line, key string) bool {
	s := strings.TrimLeft(line, " \t")
	// Strip leading comment characters and spaces.
	s = strings.TrimLeft(s, "#")
	s = strings.TrimLeft(s, " \t")
	// Must start exactly with the key followed by optional spaces then '='.
	if !strings.HasPrefix(s, key) {
		return false
	}
	rest := s[len(key):]
	rest = strings.TrimLeft(rest, " \t")
	return strings.HasPrefix(rest, "=")
}

// validateKeyValue checks that a value is valid for a given key definition.
func validateKeyValue(kd *configKeyDef, value string) error {
	switch kd.kind {
	case keyKindInt:
		if _, err := strconv.Atoi(value); err != nil {
			return fmt.Errorf("key %q requires an integer value, got: %q", kd.name, value)
		}
	case keyKindBool:
		switch strings.ToLower(value) {
		case "true", "false", "1", "0", "yes", "no":
		default:
			return fmt.Errorf("key %q requires a boolean value (true/false), got: %q", kd.name, value)
		}
	}
	// Key-specific validation beyond the generic kind/allowlist checks.
	if kd.name == "model" {
		if err := validateModelValue(value); err != nil {
			return err
		}
	}
	// Allowlist check for string and int keys that have one.
	if len(kd.allowed) > 0 && kd.kind != keyKindBool {
		if !containsStr(kd.allowed, value) {
			return fmt.Errorf("key %q value %q is not valid\n\nAllowed: %s",
				kd.name, value, strings.Join(kd.allowed, ", "))
		}
	}
	return nil
}

// formatTOMLValue formats a CLI string value as a TOML literal for the given key kind.
func formatTOMLValue(kd *configKeyDef, value string) (string, error) {
	switch kd.kind {
	case keyKindString:
		return fmt.Sprintf("%q", value), nil
	case keyKindInt:
		n, err := strconv.Atoi(value)
		if err != nil {
			return "", fmt.Errorf("key %q requires an integer value", kd.name)
		}
		return strconv.Itoa(n), nil
	case keyKindBool:
		switch strings.ToLower(value) {
		case "true", "1", "yes":
			return "true", nil
		case "false", "0", "no":
			return "false", nil
		default:
			return "", fmt.Errorf("key %q requires a boolean value", kd.name)
		}
	}
	return "", fmt.Errorf("unknown key kind for %q", kd.name)
}

// ─── config validate ─────────────────────────────────────────────────────────

func cmdConfigValidate() error {
	path := configPath()

	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			fmt.Printf("%s No config file found at %s\n", yellow("⚠"), path)
			fmt.Printf("  Run %s to create one.\n", bold("nav-pilot config init"))
			return nil
		}
		return fmt.Errorf("reading config: %w", err)
	}

	var cfg Config
	meta, parseErr := toml.Decode(string(data), &cfg)
	if parseErr != nil {
		fmt.Printf("%s TOML parse error: %v\n", red("✗"), parseErr)
		return fmt.Errorf("config file has invalid TOML syntax")
	}

	var problems []string

	// Unknown keys (keys in file not recognized by nav-pilot).
	for _, key := range meta.Undecoded() {
		problems = append(problems, fmt.Sprintf("unknown key: %s", strings.Join(key, ".")))
	}

	// Semantic validation — append the []string slice directly.
	problems = append(problems, validateConfigProblems(&cfg)...)

	if len(problems) == 0 {
		fmt.Printf("%s Config is valid (%s)\n", green("✓"), path)
		return nil
	}

	fmt.Printf("%s Config has %d problem(s) (%s):\n", red("✗"), len(problems), path)
	for _, p := range problems {
		fmt.Printf("  - %s\n", p)
	}
	return fmt.Errorf("config validation failed")
}

// ─── config explain ──────────────────────────────────────────────────────────

func cmdConfigExplain(key string) error {
	cfg, err := readConfig()
	if err != nil {
		return err
	}
	resolved := resolve(cfg, CLIOverrides{})

	if key != "" {
		kd := findKeyDef(key)
		if kd == nil {
			return fmt.Errorf("unknown key: %q\n\nKnown keys: %s", key, knownKeyNames())
		}
		printKeyExplain(kd, resolved)
		return nil
	}

	// Print all keys.
	for i := range configKeyDefs {
		if i > 0 {
			fmt.Println()
		}
		printKeyExplain(&configKeyDefs[i], resolved)
	}
	return nil
}

func printKeyExplain(kd *configKeyDef, resolved ResolvedConfig) {
	fmt.Printf("  %s\n", bold(kd.name))
	fmt.Printf("    %s\n", kd.description)
	if len(kd.allowed) > 0 {
		fmt.Printf("    Allowed:  %s\n", strings.Join(kd.allowed, ", "))
	} else if kd.kind == keyKindBool {
		fmt.Printf("    Allowed:  true, false\n")
	} else if kd.name == "model" {
		var ids []string
		for _, p := range allProviders() {
			for _, m := range p.KnownModels() {
				ids = append(ids, m.ID)
			}
		}
		fmt.Printf("    Common:   %s\n", strings.Join(ids, ", "))
		fmt.Printf("    Allowed:  any well-formed id ([A-Za-z0-9._/-], e.g. provider/model for opencode)\n")
	} else {
		fmt.Printf("    Allowed:  any non-empty string\n")
	}
	if kd.defaultVal != "" {
		fmt.Printf("    Default:  %s\n", kd.defaultVal)
	} else {
		fmt.Printf("    Default:  (unset)\n")
	}
	if kd.flag != "" {
		fmt.Printf("    CLI flag: %s\n", kd.flag)
	}

	val := resolvedFieldStr(resolved, kd.name)
	if val == "" {
		fmt.Printf("    Current:  (unset)\n")
	} else {
		fmt.Printf("    Current:  %s\n", val)
	}
	fmt.Printf("    To set:   nav-pilot config set %s <value>\n", kd.name)
}
