apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "my-copilot"
  namespace: "copilot"
  annotations:
    "nais.io/run-as-group": "65532"
    "nais.io/run-as-user": "65532"
spec:
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        groups:
          - id: 48120347-8582-4329-8673-7beb3ed6ca06 # dev
          - id: 76e9ee7e-2cd1-4814-b199-6c0be007d7b4 # dev
          - id: eb5c5556-6c9a-4e54-83fc-f70cae25358d # dev
          - id: 879f302e-73e9-48bf-8103-16edd8606c4a # infra
          - id: afcbfed4-d5d4-4964-8db5-f59b6f61b929 # azure
          - id: 8396d3ec-e263-49c7-b72a-87440d7ee3f4 # design
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
      - /_next/**
      - /*.svg
      - /favicon.ico
      - /install/**
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
  envFrom:
    - secret: my-copilot
  env:
    - name: "NODE_ENV"
      value: "production"
    - name: "GITHUB_ORG"
      value: "navikt"
    - name: "NEXT_TELEMETRY_DISABLED"
      value: "1"
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_METRICS_ENABLED
      value: "true"
    - name: OTEL_METRICS_EXEMPLAR_FILTER
      value: ALWAYS_ON
    - name: MCP_REGISTRY_URL
      value: "{{mcp_registry_url}}"
  liveness:
    path: "/health"
    port: 3000
  readiness:
    path: "/health"
    port: 3000
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: "/metrics"
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "10m"
      memory: "128Mi"
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
        - host: {{mcp_registry_host}}
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
