import type { NewsItem } from "@/lib/news-types";

export const storyNewsItems: NewsItem[] = [
  {
    slug: "copilot-chat-enterprise-rollout",
    title: "Copilot Chat rulles ut bredere i juni",
    date: "2026-06-24",
    draft: false,
    category: "copilot",
    excerpt: "GitHub lanserer flere arbeidsflyter for team som bruker Copilot Chat i organisasjonskontekst.",
    tags: ["copilot", "chat"],
    type: "link",
    url: "https://github.blog/changelog/2026-06-24-copilot-chat-rollout/",
    author: "github",
  },
  {
    slug: "nav-pilot-workflows",
    title: "nav-pilot får tydeligere arbeidsflyt for oppstart",
    date: "2026-06-22",
    draft: false,
    category: "nav-pilot",
    excerpt: "Vi samlet de viktigste startpunktene for nye bidragsytere i nav-pilot-økosystemet.",
    tags: ["nav-pilot", "workflow"],
    type: "article",
    content: "Story fixture",
    author: "starefossen",
  },
  {
    slug: "praksis-reusable-components",
    title: "Gjenbrukbare komponenter gjør stories og pages enklere å holde konsistent",
    date: "2026-06-20",
    draft: false,
    category: "praksis",
    excerpt: "En liten komponentflate gir lavere vedlikeholdskostnad og færre kopierte mønstre.",
    tags: ["praksis", "components"],
    type: "article",
    content: "Story fixture",
    author: "starefossen",
  },
  {
    slug: "nav-security-update",
    title: "Oppdatert sikkerhetsveiledning for token-håndtering",
    date: "2026-06-18",
    draft: false,
    category: "nav",
    excerpt: "Vi justerte anbefalingene for hvordan tokens og headers skal behandles i Nav-applikasjoner.",
    tags: ["nav", "security"],
    type: "link",
    url: "https://example.com/nav-security-update",
  },
  {
    slug: "copilot-summary-preview",
    title: "Månedssammendraget blir publisert når juni er over",
    date: "2026-06-28",
    draft: false,
    category: "oppsummering",
    excerpt: "Juni-saker skal stå som egne artikler frem til måneden er ferdig.",
    tags: ["oppsummering"],
    type: "article",
    content: "Story fixture",
  },
  {
    slug: "nav-pilot-feedback",
    title: "Tilbakemeldinger fra teamene peker på mer konsistente startfliser",
    date: "2026-06-26",
    draft: false,
    category: "nav-pilot",
    excerpt: "Vi har oppdatert strukturen for oppstartsfliser og landing pages basert på tilbakemeldinger.",
    tags: ["nav-pilot", "ux"],
    type: "link",
    url: "https://example.com/nav-pilot-feedback",
    author: "navikt",
  },
];
