// Command generate-retired records every artifact the source has ever
// published and later deleted, together with the content hashes those files
// carried.
//
// Why this file has to exist at all: `nav-pilot sync` removes only what its
// state file says it wrote, which is the right rule (a file the user edited
// must survive), but it leaves an artifact retired upstream on disk forever.
// Three agents retired in #481 were still installed on a developer machine in
// September, one of them pinned to a model GitHub had withdrawn (#716).
//
// The evidence for "nav-pilot wrote this, and it is gone now" is in the source
// repo's own git history: if an installed file's content equals a blob that
// path once had, nav-pilot published it. A hand-written agent that happens to
// share the name does not match, so it is never touched.
//
// But history is not available where it is needed. `nav-pilot` fetches a
// repo-shaped source with --depth 1 (internal/source/source.go), so a user
// syncing from navikt/copilot has no history to query, and users are exactly
// who has the orphans. This generator lifts the answer out of history and
// commits it, so a shallow clone carries it.
//
// Generated, not maintained: nobody has to remember to add a name while they
// are busy deleting one, which was the objection to keeping such a list by
// hand.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// artifactDirs are the trees whose deletions matter. A file outside them is not
// something nav-pilot installs.
var artifactDirs = []string{"agents", "skills", "instructions", "prompts", "hooks", "extensions"}

const outputPath = ".nav-pilot/retired-artifacts.json"

// document is the generated file. Sorted throughout, so regenerating without a
// history change produces a byte-identical file and the CI check means
// something.
type document struct {
	Comment string              `json:"_comment"`
	Paths   map[string][]string `json:"paths"`
}

func main() {
	check := flag.Bool("check", false, "verify the committed file matches history, and exit 2 if not")
	flag.Parse()

	// git pathspecs and the working-tree check are both relative to the process
	// working directory, so anchor to the repo root: `go run .` from the tool's
	// own directory would otherwise ask git about scripts/generate-retired/agents
	// and report that nothing was ever retired.
	root, err := git("rev-parse", "--show-toplevel")
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate-retired: not inside a git repository: %v\n", err)
		os.Exit(1)
	}
	if err := os.Chdir(strings.TrimSpace(root)); err != nil {
		fmt.Fprintf(os.Stderr, "generate-retired: %v\n", err)
		os.Exit(1)
	}

	doc, err := build()
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate-retired: %v\n", err)
		os.Exit(1)
	}
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate-retired: %v\n", err)
		os.Exit(1)
	}
	out = append(out, '\n')

	if *check {
		have, err := os.ReadFile(outputPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "generate-retired: %s is missing; run mise run retired:generate\n", outputPath)
			os.Exit(2)
		}
		if string(have) != string(out) {
			fmt.Fprintf(os.Stderr, "generate-retired: %s is out of date; run mise run retired:generate\n", outputPath)
			os.Exit(2)
		}
		fmt.Printf("   %s is current (%d retired path(s))\n", outputPath, len(doc.Paths))
		return
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "generate-retired: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outputPath, out, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "generate-retired: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("   %s (%d retired path(s))\n", outputPath, len(doc.Paths))
}

func build() (*document, error) {
	doc := &document{
		Comment: "Generated by scripts/generate-retired. Artifact paths the source has published and since deleted, with every content hash they carried. nav-pilot uses this to remove an installed artifact it published and then retired, and only when the content matches: a file someone wrote themselves never does. Regenerate with: mise run retired:generate",
		Paths:   map[string][]string{},
	}
	for _, dir := range artifactDirs {
		deleted, err := deletedPaths(dir)
		if err != nil {
			return nil, err
		}
		for _, p := range deleted {
			// A path deleted and later re-added is not retired. Present in the
			// working tree wins over anything history says.
			if _, err := os.Stat(p); err == nil {
				continue
			}
			blobs, err := blobsFor(p)
			if err != nil {
				return nil, err
			}
			if len(blobs) > 0 {
				doc.Paths[p] = blobs
			}
		}
	}
	return doc, nil
}

// deletedPaths lists every path under dir that some commit deleted.
func deletedPaths(dir string) ([]string, error) {
	out, err := git("log", "--all", "--diff-filter=D", "--format=", "--name-only", "--", dir+"/")
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	var paths []string
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || !strings.HasPrefix(line, dir+"/") || seen[line] {
			continue
		}
		seen[line] = true
		paths = append(paths, line)
	}
	sort.Strings(paths)
	return paths, nil
}

// blobsFor returns every distinct blob hash the path has held, oldest listing
// order made deterministic by sorting.
func blobsFor(path string) ([]string, error) {
	commits, err := git("log", "--all", "--format=%H", "--", path)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	var blobs []string
	for _, c := range strings.Fields(commits) {
		out, err := git("ls-tree", c, "--", path)
		if err != nil {
			return nil, err
		}
		for _, line := range strings.Split(out, "\n") {
			fields := strings.Fields(line)
			if len(fields) < 3 || seen[fields[2]] {
				continue
			}
			seen[fields[2]] = true
			blobs = append(blobs, fields[2])
		}
	}
	sort.Strings(blobs)
	return blobs, nil
}

// git runs one git command and keeps stderr on failure. cmd.Output() discards
// it, which turns "not a git repository" and "bad revision" alike into a bare
// "exit status 128" and leaves nothing to act on, locally or in CI.
func git(args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		if msg := strings.TrimSpace(stderr.String()); msg != "" {
			return "", fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, msg)
		}
		return "", fmt.Errorf("git %s: %w", strings.Join(args, " "), err)
	}
	return string(out), nil
}
